### ISSUE TITLE
Pagination : Redirect to current page

### ISSUE THREAD

**Issue by atiar-cse** [niiknow/vue-datatables-net#14]
Hi,

Suppose - when editing an item from page no 3, and once update button was clicked it reloading the table from first page.

Also same things is happening when clicked "Back" button on the below url.
https://laratt.niiknow.org/home/contact/35/edit

I am looking the parameters or methods - if there is a way to get back into that current page. By collecting the page no. info e.g. "const parms = this.$refs.table.getServerParams()".

Package Version : "vue-datatables-net": "^1.1.4"

Thanks in advance!

**Comment by noogen** [comment]
One benefit of using jQuery Datatables is the many out-of-the box functionalities it provide.  To save state, simply provide the option: `opts: { stateSave: true }` ref: https://datatables.net/reference/option/stateSave

Again, to summarize the ref link above, this is saving state by the table id, so simply add an `id` attribute to the table object: https://github.com/niiknow/vue-datatables-net/blob/master/src/VdtnetTable.vue#L5

Otherwise, use the two callback functions `stateSaveCallback` and `stateLoadCallback` in combination with `saveState: true`

**Comment by noogen** [comment]
After responding to your question, I realized I didn't have an id on my table so I've add it and deploy as 1.1.5

**Comment by atiar-cse** [comment]
Thank you - It's working nicely...
