### ISSUE TITLE
Cannot use the jQuery Datatables responsive plugin

### ISSUE THREAD

**Issue by vibonacci** [niiknow/vue-datatables-net#19]
Hi, 

I'm passing responsive: true to my tables. However, the plugin is not triggered. Do I need to load it separately, and if so, how?

Thanks in advance

**Comment by noogen** [comment]
You need to install the responsive plugin and the specific theme.  Also remember to load the CSS because there's where the blue "plus" icon come from.  I added the example https://github.com/niiknow/vue-datatables-net/blob/master/example/responsive.vue#L82

Line 82 and 83 load the plugin and specific theme, bootstrap4 theme in this case.   Then line 91 load the css for it.

 ```
npm install --save-dev datatables.net-responsive datatables.net-responsive-bs4
```

Also note that our Master/Details implementation does not work well with responsive because it uses the same child table row, per my note here: https://github.com/niiknow/vue-datatables-net#responsive

**Comment by vibonacci** [comment]
Thank you for the extensive explanation. We got it to work now and it works great. 

1 tip for others: on the following page you can make a 'combined-module' so you do not need to load responsive plugin separately.

https://datatables.net/download/

I'll take this opportunity to thank you for making this wrapper. We love Vue and we love datatables.net. We always used datatables.net, but had troubles getting it to work after switching to Vue. Vue and jQ do not go well together naturally. Your wrapper solved this perfectly 🙂

**Comment by vibonacci** [comment]
![image](https://user-images.githubusercontent.com/9674553/66683925-01636580-ec79-11e9-85bf-2d13f67a2558.png)
