### ISSUE TITLE
Is it possible to data load with Axios?

### ISSUE THREAD

**Issue by yurenlimbu** [niiknow/vue-datatables-net#60]
Really great plugin!

I want to use this plugin for my Vue project. Is it possible to load data-table with Axios? If it possible then how can I start?

Thanks!

**Comment by noogen** [comment]
Since this is a wrapper around jQuery datatable plugin, jQuery use of ajax is best.  If you want to use Axios, you have to do many things manually include ajax call and manual parameters mapping.

You can load the data by Axios and use `setTableData` function: https://github.com/niiknow/vue-datatables-net/blob/master/src/VdtnetTable.vue#L652

You can provide a `dataLoader` function with a callback function: https://github.com/niiknow/vue-datatables-net/blob/master/src/VdtnetTable.vue#L180
```js
function myDataLoader(callback) {
  // do you ajax by axios
  // get your response array as data
  // call callback with data
  callback(data);
}
```

========
P.S.

If you're doing things manually, I suggest you can look into using bootstrap-vue b-table and https://github.com/niiknow/bvtnet-items-provider
